name: Build PeDitXOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          apt-get update
          apt-get install -y squashfs-tools xorriso curl dialog parted coreutils dd nano unzip gzip openssh-server python3 python3-pip

      - name: Install dependencies for Python script
        run: |
          pip3 install subprocess

      - name: Download and mount ISO using Python script
        run: |
          curl -L -o debian.iso https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.0.0-amd64-netinst.iso
          mkdir -p /mnt
          mkdir -p /tmp/live-iso
          python3 ./scripts/mount_iso.py

      - name: Copy PeDitXrt_installer.sh and add it to startup
        run: |
          # Copy the installer script to the live system
          cp ./scripts/PeDitXrt_installer.sh /tmp/live-iso/root/
          chmod +x /tmp/live-iso/root/PeDitXrt_installer.sh
          
          # Add the script to init.d
          mkdir -p /tmp/live-iso/etc/init.d
          echo -e "#!/bin/bash\n/tmp/live-iso/root/PeDitXrt_installer.sh" | tee /tmp/live-iso/etc/init.d/pe_dit_x_installer
          chmod +x /tmp/live-iso/etc/init.d/pe_dit_x_installer
          
          # Enable the script to run at startup
          chroot /tmp/live-iso update-rc.d pe_dit_x_installer defaults

      - name: Create the live ISO
        run: |
          # Create the live ISO after mounting and copying the content
          xorriso -as mkisofs -o PeDitXOS.iso -r -J -V "PeDitXOS" /tmp/live-iso

      - name: Upload PeDitXOS ISO to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PeDitXOS
          path: PeDitXOS.iso
