name: Run maker.py on Alpine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-maker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Alpine container
      uses: docker://python:3.9-alpine

    - name: Install dependencies
      run: |
        apk update
        apk add --no-cache python3 py3-pip

    - name: Run maker.py
      run: |
        python3 scripts/maker.py
