name: Build PeDitXOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker container
        run: |
          # Pull the Alpine image
          docker pull alpine:3.16
          # Run a container in the background
          docker run -d --name my_container alpine:3.16 tail -f /dev/null

      - name: Install packages in Docker container
        run: |
          # Install necessary packages inside the container
          docker exec my_container apk update
          docker exec my_container apk add parted util-linux curl unzip nano bash

      - name: Copy files and run script inside Docker container
        run: |
          # Copy necessary files into the container
          docker cp ./scripts/PeDitXrt_installer.sh my_container:/root/
          # Give execute permission to the script
          docker exec my_container chmod +x /root/PeDitXrt_installer.sh
          # Run the script inside the container
          docker exec my_container /root/PeDitXrt_installer.sh

      - name: Create live ISO
        run: |
          # Create the live ISO from inside the container
          docker exec my_container sh -c "xorriso -as mkisofs -o /tmp/PeDitXOS.iso -r -J -V 'PeDitXOS' /root"
        
      - name: Upload PeDitXOS ISO to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PeDitXOS
          path: /tmp/PeDitXOS.iso
