name: Build PeDitXOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          # نصب ابزارهای مورد نیاز برای ساخت ISO
          sudo apt-get update
          sudo apt-get install -y squashfs-tools xorriso curl dialog parted coreutils nano unzip gzip openssh-server

      - name: Create live ISO with custom banner, scripts, and OpenSSH
        run: |
          # ایجاد دایرکتوری کاری
          mkdir -p live-iso

          # دانلود و نصب Debian netinst ISO
          curl -L -o debian.iso https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.7.0-amd64-netinst.iso
          
          # ماؤن کردن ISO
          sudo mount -o loop debian.iso /mnt
          
          # کپی کردن محتویات ISO به دایرکتوری کاری
          sudo cp -a /mnt/. live-iso/
          
          # نصب Plymouth و بنر سفارشی
          sudo apt-get install -y plymouth
          sudo mkdir -p /tmp/live-iso/usr/share/plymouth/themes/mytheme
          curl -L -o /tmp/live-iso/usr/share/plymouth/themes/mytheme/banner.png https://raw.githubusercontent.com/peditx/luci-theme-peditx/refs/heads/main/luasrc/style/brand.png
          echo -e 'theme="mytheme"\n' | sudo tee -a /tmp/live-iso/etc/plymouth/plymouthd.conf
          
          # کپی کردن اسکریپت به سیستم زنده
          sudo cp ./PeDitXrt_installer.sh /tmp/live-iso/root/
          
          # اعطای مجوز اجرایی به اسکریپت
          sudo chmod +x /tmp/live-iso/root/PeDitXrt_installer.sh
          
          # نصب ابزارهای ضروری
          sudo mkdir -p /tmp/live-iso/usr/bin
          sudo cp /usr/bin/resize2fs /tmp/live-iso/usr/bin/
          sudo cp /usr/bin/gzip /tmp/live-iso/usr/bin/
          sudo cp /usr/bin/unzip /tmp/live-iso/usr/bin/
          sudo cp /usr/bin/curl /tmp/live-iso/usr/bin/
          sudo cp /usr/bin/wget /tmp/live-iso/usr/bin/
          sudo cp /usr/bin/nano /tmp/live-iso/usr/bin/
          sudo cp /usr/bin/parted /tmp/live-iso/usr/bin/
          sudo cp /usr/bin/dd /tmp/live-iso/usr/bin/

          # نصب OpenSSH Server
          sudo mkdir -p /tmp/live-iso/etc/ssh
          sudo cp /etc/ssh/sshd_config /tmp/live-iso/etc/ssh/
          sudo mkdir -p /tmp/live-iso/etc/init.d
          echo -e "#!/bin/bash\nservice ssh start" | sudo tee /tmp/live-iso/etc/init.d/start_ssh
          sudo chmod +x /tmp/live-iso/etc/init.d/start_ssh
          
          # فعال کردن سرویس SSH برای شروع در بوت
          sudo chroot /tmp/live-iso update-rc.d start_ssh defaults
          
          # ساخت ISO نهایی
          sudo xorriso -as mkisofs -o PeDitXOS.iso -r -J -V "PeDitXOS" /tmp/live-iso
          
      - name: Upload PeDitXOS ISO to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PeDitXOS
          path: PeDitXOS.iso
