name: Build and Upload ISO

on:
  push:
    branches:
      - main

jobs:
  build-and-upload-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Finnix ISO
        run: |
          wget http://mirror.aarnet.edu.au/pub/finnix/120/finnix-120.iso -O original.iso

      - name: Mount ISO
        run: |
          sudo mkdir /mnt/iso
          sudo mount -o loop original.iso /mnt/iso

      - name: Modify Boot Logo
        run: |
          sudo wget -O /mnt/iso/boot/grub/splash.png https://peditx.ir/wp-content/uploads/2023/05/lastg-logo.png

      - name: Unmount ISO
        run: |
          sudo umount /mnt/iso
          sudo rmdir /mnt/iso

      - name: Generate Modified ISO
        run: |
          xorriso -as mkisofs -o PeDitXOs.iso -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -c isolinux/boot.cat -b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table iso

      - name: Upload ISO File
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: PeDitXOs ISO
          path: PeDitXOs.iso
