name: Build and Customize Debian ISO
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete previous artifacts
        run: |
          rm -rf ${{ github.workspace }}/custom-debian.iso

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools genisoimage wget

      - name: Download Debian Netinst ISO
        run: |
          wget -O debian-netinst.iso https://deb.debian.org/debian/dists/bullseye/main/installer-i386/current/images/netboot/mini.iso

      - name: Mount ISO
        run: |
          mkdir iso
          sudo mount -o loop debian-netinst.iso iso

      - name: Extract ISO contents
        run: |
          mkdir extracted
          rsync -a iso/ extracted/

      - name: Customize ISO
        run: |
          sudo chroot extracted/ /bin/bash -c "apt-get update && apt-get install -y wget curl nano vi parted resize2fs"

      - name: Repack ISO
        run: |
          sudo genisoimage -o custom-debian.iso -r -J -no-emul-boot -boot-load-size 4 -boot-info-table -b isolinux/isolinux.bin -c isolinux/boot.cat extracted/

      - name: Cleanup
        run: |
          sudo umount iso
          rm -rf iso extracted debian-netinst.iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v2
        with:
          name: Custom Debian Netinst ISO
          path: custom-debian.iso
