name: Build and Customize Live Tiny Core Linux ISO
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl squashfs-tools genisoimage

      - name: Download Tiny Core Linux base system
        run: |
          wget https://www.ibiblio.org/pub/linux/distributions/tinycorelinux/12.x/x86/release/Core-current.iso -O tinycore.iso

      - name: Mount Tiny Core Linux ISO
        run: |
          sudo mkdir /mnt/iso
          sudo mount -o loop tinycore.iso /mnt/iso

      - name: Customize Tiny Core Linux
        run: |
          # Add code to customize the mounted Tiny Core Linux system
          # For example, you can add or modify files, packages, configurations, etc.
          sudo chroot /mnt/iso /bin/sh -c "tce-load -wi micro"

      - name: Unmount Tiny Core Linux ISO
        run: |
          sudo umount /mnt/iso
          sudo rm -rf /mnt/iso

      - name: Create ISO
        run: |
          sudo mkisofs -quiet -l -J -R -V TC_CUSTOM -no-emul-boot -boot-load-size 4 -boot-info-table -b isolinux/isolinux.bin -c isolinux/boot.cat -o tinycore-custom.iso .

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v2
        with:
          name: Custom Tiny Core Linux ISO
          path: tinycore-custom.iso
