name: Build and Customize Alpine Linux Live ISO
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete previous artifacts
        run: |
          rm -rf ${{ github.workspace }}/.github/workflows/custom-alpine.iso

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl squashfs-tools genisoimage

      - name: Download Alpine Linux base system
        run: |
          wget https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86/alpine-netboot-3.18.0-x86.tar.gz -O alpine-base.iso

      - name: Mount Alpine Linux ISO
        run: |
          sudo mkdir /mnt/iso
          sudo mount -o loop alpine-base.iso /mnt/iso

      - name: Customize Alpine Linux
        run: |
          # Add code to customize the mounted Alpine Linux system
          # For example, you can add or modify files, packages, configurations, etc.
          sudo chroot /mnt/iso /bin/sh -c "apk update && apk add package1 package2 ..."

      - name: Unmount Alpine Linux ISO
        run: |
          sudo umount /mnt/iso
          sudo rm -rf /mnt/iso

      - name: Create ISO
        run: |
          sudo mkisofs -quiet -l -J -R -V CUSTOM -no-emul-boot -boot-load-size 4 -boot-info-table -b isolinux/isolinux.bin -c isolinux/boot.cat -o custom-alpine.iso .

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v2
        with:
          name: Custom Alpine Linux ISO
          path: custom-alpine.iso
