name: Build ISO

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_iso:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install necessary tools
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools genisoimage

      - name: Download and execute script
        run: |
          wget -O start.sh https://peditx.ir/rt/start.sh
          chmod +x start.sh
          ./start.sh

      - name: Create ISO file
        run: |
          sudo mksquashfs <path_to_linux_directory> custom.iso

      - name: Upload ISO file
        uses: actions/upload-artifact@v2
        with:
          name: custom-iso
          path: custom.iso
