name: Build and Customize Debian Live ISO
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete previous artifacts
        run: |
          rm -rf ${{ github.workspace }}/.github/workflows/custom-debian.iso

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl genisoimage squashfs-tools

      - name: Download Debian Live base system
        run: |
          wget https://cdimage.debian.org/debian-cd/current/i386/iso-cd/debian-11.7.0-i386-netinst.iso -O debian-live.iso

      - name: Mount Debian Live ISO
        run: |
          sudo mkdir /mnt/iso
          sudo mount -o loop debian-live.iso /mnt/iso

      - name: Customize Debian Live
        run: |
          # Add code to customize the mounted Debian Live system
          # For example, you can add or modify files, packages, configurations, etc.
          sudo chroot /mnt/iso /bin/bash -c "apt-get update && apt-get install -y package1 package2 ..."

      - name: Unmount Debian Live ISO
        run: |
          sudo umount /mnt/iso
          sudo rm -rf /mnt/iso

      - name: Create ISO
        run: |
          sudo mkisofs -quiet -l -J -R -V CUSTOM -no-emul-boot -boot-load-size 4 -boot-info-table -b isolinux/isolinux.bin -c isolinux/boot.cat -o custom-debian.iso .

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v2
        with:
          name: Custom Debian Live ISO
          path: custom-debian.iso
