name: Build PeDitXOs ISO with Alpine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y xorriso squashfs-tools grub-efi grub-common efibootmgr isolinux syslinux-common zstd

    - name: Create minimal Alpine filesystem
      run: |
        wget http://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-minirootfs-3.18.0-x86_64.tar.gz
        mkdir -p ./PeDitXOs-rootfs
        sudo tar -xzf alpine-minirootfs-3.18.0-x86_64.tar.gz -C ./PeDitXOs-rootfs

    - name: Install additional software
      run: |
        sudo chroot ./PeDitXOs-rootfs /bin/sh -c "apk update && apk add nano parted gzip curl wget fdisk dialog grub efibootmgr linux-lts"

    - name: Download installer script
      run: |
        sudo wget https://raw.githubusercontent.com/peditx/PeDitXOs/refs/heads/main/scripts/PeDitXrt_installer.sh -O ./PeDitXOs-rootfs/root/PeDitXrt_installer.sh
        sudo chmod +x ./PeDitXOs-rootfs/root/PeDitXrt_installer.sh

    - name: Set up startup script using rc.local
      run: |
        echo "#!/bin/sh -e" | sudo tee ./PeDitXOs-rootfs/etc/rc.local
        echo "/root/PeDitXrt_installer.sh" | sudo tee -a ./PeDitXOs-rootfs/etc/rc.local
        sudo chmod +x ./PeDitXOs-rootfs/etc/rc.local

    - name: Create ISO image
      run: |
        sudo xorriso -as mkisofs \
          -o PeDitXOs.iso \
          -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
          -c isolinux/boot.cat \
          -b isolinux/isolinux.bin \
          -no-emul-boot -boot-load-size 4 -boot-info-table \
          -eltorito-alt-boot \
          -e boot/grub/efi.img \
          -no-emul-boot \
          -isohybrid-gpt-basdat \
          ./PeDitXOs-rootfs

    - name: Upload ISO as artifact
      uses: actions/upload-artifact@v3
      with:
        name: PeDitXOs.iso
        path: PeDitXOs.iso
