name: Build PeDitXOs ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y debootstrap xorriso squashfs-tools grub-efi grub-common efibootmgr isolinux syslinux-common

    - name: Create minimal Linux filesystem
      run: |
        sudo debootstrap --variant=minbase --include=nano,parted,gzip,curl,wget,fdisk,whiptail,dialog,systemd,grub-efi,efibootmgr stable ./PeDitXOs-rootfs http://deb.debian.org/debian

    - name: Install additional software
      run: |
        sudo chroot ./PeDitXOs-rootfs apt-get update
        sudo chroot ./PeDitXOs-rootfs apt-get install -y nano parted gzip curl wget fdisk whiptail dialog systemd grub-efi efibootmgr linux-image-amd64 linux-headers-amd64 live-boot

    - name: Install lz4 tool
      run: |
        sudo chroot ./PeDitXOs-rootfs apt-get update
        sudo chroot ./PeDitXOs-rootfs apt-get install -y lz4

    - name: Download installer script
      run: |
        sudo wget https://raw.githubusercontent.com/peditx/PeDitXOs/refs/heads/main/scripts/PeDitXrt_installer.sh -O ./PeDitXOs-rootfs/root/PeDitXrt_installer.sh
        sudo chmod +x ./PeDitXOs-rootfs/root/PeDitXrt_installer.sh

    - name: Set up startup script using rc.local
      run: |
        echo "#!/bin/sh -e" | sudo tee ./PeDitXOs-rootfs/etc/rc.local
        echo "/root/PeDitXrt_installer.sh" | sudo tee -a ./PeDitXOs-rootfs/etc/rc.local
        sudo chmod +x ./PeDitXOs-rootfs/etc/rc.local

    - name: Set up EFI directory structure
      run: |
        sudo mkdir -p ./PeDitXOs-rootfs/boot/efi
        sudo mkdir -p ./PeDitXOs-rootfs/boot/grub
        sudo mkdir -p ./PeDitXOs-rootfs/isolinux
        sudo mkdir -p ./PeDitXOs-rootfs/live

    - name: Create and mount EFI partition
      run: |
        sudo dd if=/dev/zero of=./efi_partition.img bs=1M count=100
        sudo mkfs.vfat ./efi_partition.img
        sudo mount ./efi_partition.img ./PeDitXOs-rootfs/boot/efi

    - name: Mount necessary filesystems
      run: |
        sudo mount --bind /dev ./PeDitXOs-rootfs/dev
        sudo mount --bind /proc ./PeDitXOs-rootfs/proc
        sudo mount --bind /sys ./PeDitXOs-rootfs/sys

    - name: Download and set boot logo
      run: |
        sudo wget https://raw.githubusercontent.com/peditx/luci-theme-peditx/refs/heads/main/luasrc/brand.png -O ./PeDitXOs-rootfs/boot/grub/brand.png
        echo 'GRUB_BACKGROUND="/boot/grub/brand.png"' | sudo tee -a ./PeDitXOs-rootfs/etc/default/grub

    - name: Install GRUB for UEFI
      run: |
        sudo chroot ./PeDitXOs-rootfs grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=PeDitXOs --removable
        sudo chroot ./PeDitXOs-rootfs update-grub

    - name: Create initrd.img
      run: |
        sudo chroot ./PeDitXOs-rootfs mkinitramfs -c lz4 -o /boot/initrd.img $(ls ./PeDitXOs-rootfs/boot/vmlinuz* | grep -oP 'vmlinuz-\d+\.\d+\.\d+.*' | head -n 1)

    - name: Create SquashFS filesystem
      run: |
        sudo mksquashfs ./PeDitXOs-rootfs ./PeDitXOs-rootfs/live/filesystem.squashfs -comp xz

    - name: Create EFI image
      run: |
        sudo mkdir -p ./PeDitXOs-rootfs/boot/grub
        sudo cp -r /usr/lib/grub/x86_64-efi/* ./PeDitXOs-rootfs/boot/grub/
        sudo grub-mkimage -o ./PeDitXOs-rootfs/boot/grub/efi.img -O x86_64-efi -p /boot/grub part_gpt part_msdos fat ext2 iso9660

    - name: Copy ISOLINUX files
      run: |
        sudo cp /usr/lib/ISOLINUX/isohdpfx.bin ./PeDitXOs-rootfs/isolinux/
        sudo cp /usr/lib/ISOLINUX/isolinux.bin ./PeDitXOs-rootfs/isolinux/
        sudo cp /usr/lib/syslinux/modules/bios/ldlinux.c32 ./PeDitXOs-rootfs/isolinux/

    - name: Create ISOLINUX configuration
      run: |
        echo 'DEFAULT linux' | sudo tee ./PeDitXOs-rootfs/isolinux/isolinux.cfg
        echo 'LABEL linux' | sudo tee -a ./PeDitXOs-rootfs/isolinux/isolinux.cfg
        echo '  KERNEL /boot/vmlinuz' | sudo tee -a ./PeDitXOs-rootfs/isolinux/isolinux.cfg
        echo '  APPEND initrd=/boot/initrd.img boot=live components quiet splash' | sudo tee -a ./PeDitXOs-rootfs/isolinux/isolinux.cfg

    - name: Create GRUB configuration
      run: |
        echo 'set timeout=0' | sudo tee ./PeDitXOs-rootfs/boot/grub/grub.cfg
        echo 'menuentry "PeDitXOs" {' | sudo tee -a ./PeDitXOs-rootfs/boot/grub/grub.cfg
        echo '  linux /boot/vmlinuz boot=live components quiet splash' | sudo tee -a ./PeDitXOs-rootfs/boot/grub/grub.cfg
        echo '  initrd /boot/initrd.img' | sudo tee -a ./PeDitXOs-rootfs/boot/grub/grub.cfg
        echo '}' | sudo tee -a ./PeDitXOs-rootfs/boot/grub/grub.cfg

    - name: Unmount filesystems
      run: |
        sudo umount ./PeDitXOs-rootfs/boot/efi
        sudo umount ./PeDitXOs-rootfs/dev
        sudo umount ./PeDitXOs-rootfs/proc
        sudo umount ./PeDitXOs-rootfs/sys

    - name: Create ISO image
      run: |
        sudo xorriso -as mkisofs \
          -o PeDitXOs.iso \
          -isohybrid-mbr ./PeDitXOs-rootfs/isolinux/isohdpfx.bin \
          -c isolinux/boot.cat \
          -b isolinux/isolinux.bin \
          -no-emul-boot -boot-load-size 4 -boot-info-table \
          -eltorito-alt-boot \
          -e boot/grub/efi.img \
          -no-emul-boot \
          -isohybrid-gpt-basdat \
          ./PeDitXOs-rootfs

    - name: Upload ISO as artifact
      uses: actions/upload-artifact@v3
      with:
        name: PeDitXOs.iso
        path: PeDitXOs.iso
